name: AdvancedKits
main: AdvancedKits\Main
version: 5.3
api: [3.0.0-ALPHA11]
author: luca28pet
description: Add kits to your server
website: https://github.com/luca28pet/AdvancedKits
commands:
 kit:
  description: claim a kit!
  usage: "§b/kit <kitName>"
  aliases: [kt, kits]
  permission: advancedkits.command
 akreload:
  descrpition: Reload Kits settings
  usage: "§b/akreload"
  permission: advancedkits.admin
permissions:
 advancedkits.command:
  description: "Allows the user to run /kit command"
  default: true
 advancedkits.admin:
  description: "Allows to manage admin features"
  default: op
